title: "Peer Rheinboldt"
description: "Personal academic homepage of Peer Rheinboldt, MSc Data Science student at ETH Zürich."
url: "https://peer-rh.github.io"
baseurl: ""
author:
  name: "Peer Rheinboldt"
  role: "MSc Data Science student"
  affiliation: "ETH Zürich"
  email: "peer.rheinboldt@gmail.com"
  github: "peer-rh"
  scholar: "https://scholar.google.com/citations?user=YmxzhfYAAAAJ&hl=en"
  linkedin: "peer-rheinboldt"

markdown: kramdown
highlighter: rouge

collections:
  publications:
    output: true
    permalink: /publications/:name/

defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: publication

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
